Test pr19
epfl-radio-astro/bipp pull request #20
Opened 2023-10-06 07:38 UTC by orliac

This PR mainly implements natural weighting and the possibility to consider negative eigenvalues (off by default).
Principally tested for LSQ filter (and considering negative eigenvalues) on various datasets with comparison to WSClean & CASA with OSKAR simulated data and real LOFAR and MWA data (c.f. BIPP paper). For remaining filters I only tested consistency over {SS, NUFFT} x {CPU, GPU} solutions. In all cases sensitivity corrections were not applied.

This PR also applies WEIGHT_SPECTRUM if the column is available in the MS file.

2023-11-07 09:01 UTC, AdhocMan requested changes
We now have a CI setup for testing on Piz Daint with GPUs. Could you merge the current main branch, so we test both the new CI and these changes?

2023-11-27 17:22 UTC, orliac commented on python/bipp/parameter_estimator.py
> +                if fne:
I added some inline documentation.
sigma is only considered when filtering out the negative eigenvalues (default behavior).
Also, there was a bug there as BIPP was filtering out the largest eigenvalues while it is supposed to filter the smallest eigenvalues. See https://github.com/epfl-radio-astro/bipp/pull/20/commits/53daca45397f53123c27fd65db2bee971fcf0e3f

2023-11-27 17:26 UTC, orliac commented on src/gpu/nufft_3d3.cpp
> +  opts.gpu_method = 1;
Suggestion committed.

2023-11-27 17:28 UTC, orliac commented on src/standard_synthesis.cpp
> +
Suggestion committed.

2023-11-28 15:49 UTC, orliac commented on python/bipp/frame.py
> +    offset = lim / (grid_size / 2) * 0.5
Done in https://github.com/epfl-radio-astro/bipp/pull/20/commits/ab595b4f2884506129ed5fb2f6476266d48e76eb

2024-03-18 08:56 UTC, orliac commented
Closing as out of date now with PR https://github.com/epfl-radio-astro/bipp/pull/28

2024-03-18 08:56 UTC, closed without merging